name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan-push:
    runs-on: ubuntu-latest
    environment: CODE

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Étape 3 : Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 4 : Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest .

      # Étape 5 : Lancer les tests unitaires
      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest python -m unittest discover

      # Étape 6 : Scan avec Trivy (vulnérabilités)
      - name: Scan avec Trivy (vulnérabilités)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      # Étape 7 : Scan avec Snyk (dépendances & container)
      - name: Scan avec Snyk (dépendances & container)
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Étape 8 : Scan GitLeaks (secrets dans le code)
      - name: Scan GitLeaks (secrets dans le code)
        run: |
          docker run --rm -v ${{ github.workspace }}:/code zricethezav/gitleaks:latest detect --source=/code --verbose

      # Étape 9 : Push vers Docker Hub
      - name: Push vers Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest
